### ISSUE TITLE
baichuan2扩充词表后训练报错

### ISSUE THREAD

**Issue by andrea-veritas** [seanzhang-zhichen/expand-baichuan-tokenizer#1]
baichuan2上只要扩充词表（哪怕只是加了一个token）就会报如下错误，兄弟你遇到过这种情况吗？

```
Traceback (most recent call last):
  File "/root/autodl-tmp/LLaMA-Efficient-Tuning/src/train_bash.py", line 14, in <module>
    main()
  File "/root/autodl-tmp/LLaMA-Efficient-Tuning/src/train_bash.py", line 5, in main
    run_exp()
  File "/root/autodl-tmp/LLaMA-Efficient-Tuning/src/llmtuner/tuner/tune.py", line 24, in run_exp
    run_pt(model_args, data_args, training_args, finetuning_args, callbacks)
  File "/root/autodl-tmp/LLaMA-Efficient-Tuning/src/llmtuner/tuner/pt/workflow.py", line 42, in run_pt
    train_result = trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
  File "/root/miniconda3/envs/eft/lib/python3.10/site-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/eft/lib/python3.10/site-packages/transformers/trainer.py", line 1835, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/envs/eft/lib/python3.10/site-packages/transformers/trainer.py", line 2679, in training_step
    loss = self.compute_loss(model, inputs)
  File "/root/miniconda3/envs/eft/lib/python3.10/site-packages/transformers/trainer.py", line 2704, in compute_loss
    outputs = model(**inputs)
  File "/root/miniconda3/envs/eft/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/eft/lib/python3.10/site-packages/accelerate/utils/operations.py", line 632, in forward
    return model_forward(*args, **kwargs)
  File "/root/miniconda3/envs/eft/lib/python3.10/site-packages/accelerate/utils/operations.py", line 620, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/root/miniconda3/envs/eft/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/eft/lib/python3.10/site-packages/peft/peft_model.py", line 922, in forward
    return self.base_model(
  File "/root/miniconda3/envs/eft/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Baichuan2-13B-Chat/modeling_baichuan.py", line 692, in forward
    outputs = self.model(
  File "/root/miniconda3/envs/eft/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Baichuan2-13B-Chat/modeling_baichuan.py", line 399, in forward
    self.alibi_mask = self.get_alibi_mask(
  File "/root/.cache/huggingface/modules/transformers_modules/Baichuan2-13B-Chat/modeling_baichuan.py", line 332, in get_alibi_mask
    mask = _buffered_future_mask(
  File "/root/.cache/huggingface/modules/transformers_modules/Baichuan2-13B-Chat/modeling_baichuan.py", line 59, in _buffered_future_mask
    new_future_mask = _future_mask.to(tensor)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by tuqingwen** [comment]
请问你实现baichuan2词表扩充吗?

**Comment by andrea-veritas** [comment]
> 请问你实现baichuan2词表扩充吗?

可以实现，把embed_tokens和lm_head都扩展后再训练即可。

**Comment by tuqingwen** [comment]
是否可以添加您的联系方式，向您学习下。





---原始邮件---
发件人: "Andrea ***@***.***&gt;
发送时间: 2024年12月18日(周三) 凌晨0:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [seanzhang-zhichen/expand-baichuan-tokenizer] baichuan2扩充词表后训练报错 (Issue #1)




  
请问你实现baichuan2词表扩充吗?
  
可以实现，把embed_tokens和lm_head都扩展后再训练即可。

**Comment by tuqingwen** [comment]
> > 请问你实现baichuan2词表扩充吗?
> 
> 可以实现，把embed_tokens和lm_head都扩展后再训练即可。

我的vx：18272123277
